# Generated by Django 6.0.4 on 2026-05-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_sala_nome_alter_status_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sala',
            new_name='Ambiente',
        ),
        migrations.RenameField(
            model_name='equipamento',
            old_name='sala',
            new_name='ambiente',
        ),
    ]
