# Generated by Django 6.0.4 on 2026-05-06 18:25

from django.db import migrations


def update_status_names(apps, schema_editor):
    Status = apps.get_model('inventory', 'Status')
    # Atualizar "Parcialmente" para "Atenção"
    try:
        status = Status.objects.get(nome="⚠️ Parcialmente")
        status.nome = "⚠️ Atenção"
        status.save()
    except Status.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_sala_ambiente_and_more'),
    ]

    operations = [
        migrations.RunPython(update_status_names),
    ]
